<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Establecimiento;

class EstablecimientoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Establecimiento::create(['est_id' => '0H132030','est_establecimiento' => '6090 JOSE OLAYA BALANDRA']);
        Establecimiento::create(['est_id' => '0H062070','est_establecimiento' => '6051 MERCEDES INDACOCHEA']);
        Establecimiento::create(['est_id' => '0H133085','est_establecimiento' => 'LOS INKAS']);
        Establecimiento::create(['est_id' => '0H072095','est_establecimiento' => '6044 JORGE CHAVEZ']);
        Establecimiento::create(['est_id' => '0H065030','est_establecimiento' => '7047 TACNA']);
        Establecimiento::create(['est_id' => '0H132045','est_establecimiento' => '6094 SANTA ROSA']);
        Establecimiento::create(['est_id' => '0H092005','est_establecimiento' => 'CORONEL JOSE JOAQUIN INCLAN']);
        Establecimiento::create(['est_id' => '0H111135','est_establecimiento' => '7076 LAS BRISAS DE VILLA']);
        Establecimiento::create(['est_id' => '0H052078','est_establecimiento' => '6050 JUANA ALARCO DE DAMMERT']);
        Establecimiento::create(['est_id' => '0H062075','est_establecimiento' => '6052 JOSE MARIA EGUREN']);
        Establecimiento::create(['est_id' => '0H033035','est_establecimiento' => '7083 MANUEL GONZALES PRADA']);
        Establecimiento::create(['est_id' => '0H122075','est_establecimiento' => '7038 CORAZON DE JESUS DE ARMATAMBO']);
        Establecimiento::create(['est_id' => '0H132040','est_establecimiento' => '6092 LOS REYES CATOLICOS']);
        Establecimiento::create(['est_id' => '0H101055','est_establecimiento' => 'COMUNAL SANTA ISABEL DE VILLA']);
        Establecimiento::create(['est_id' => '0H132155','est_establecimiento' => 'VIRGEN DEL MORRO SOLAR']);
        Establecimiento::create(['est_id' => '0H131120','est_establecimiento' => '7075 JUAN PABLO II']);
        Establecimiento::create(['est_id' => '0H021330','est_establecimiento' => '129']);
        Establecimiento::create(['est_id' => '0H093020','est_establecimiento' => '6005 GENERAL EMILIO SOYER CABERO']);
        Establecimiento::create(['est_id' => '0H063010','est_establecimiento' => '6051 MERCEDES INDACOCHEA']);
        Establecimiento::create(['est_id' => '0H071326','est_establecimiento' => 'COORDINACION PRONOEI - UGEL 07 SAN BORJA']);
        Establecimiento::create(['est_id' => '0H092130','est_establecimiento' => '6085 BRIGIDA SILVA DE OCHOA']);
        Establecimiento::create(['est_id' => '0H122065','est_establecimiento' => '7036 ANGELICA RECHARTE CORRALES']);
        Establecimiento::create(['est_id' => '0H031030','est_establecimiento' => '528 ALEGRIA DE JESUS']);
        Establecimiento::create(['est_id' => '0H113025','est_establecimiento' => 'TUPAC AMARU II']);
        Establecimiento::create(['est_id' => '0H133068','est_establecimiento' => '7075 JUAN PABLO II']);
        Establecimiento::create(['est_id' => '0H097015','est_establecimiento' => 'CEBA - TNTE. CRNL. PEDRO RUIZ GALLO']);
        Establecimiento::create(['est_id' => '0H035010','est_establecimiento' => 'NUESTRA SEÑORA DE LOURDES']);
        Establecimiento::create(['est_id' => '0H048035','est_establecimiento' => 'ESPECIAL SURQUILLO']);
        Establecimiento::create(['est_id' => '0H131040','est_establecimiento' => '6092 LOS REYES CATOLICOS']);
        Establecimiento::create(['est_id' => '0H028320','est_establecimiento' => 'TALENTOSOS SOBRESALIENTES']);
        Establecimiento::create(['est_id' => '0H023325','est_establecimiento' => '1128 SAN LUIS']);
        Establecimiento::create(['est_id' => '0H122095','est_establecimiento' => '7052 MARIA INMACULADA']);
        Establecimiento::create(['est_id' => '0H022310','est_establecimiento' => '0083 SAN JUAN MASIAS']);
        Establecimiento::create(['est_id' => '0H092070','est_establecimiento' => '7037 ARIOSTO MATELLINI ESPINOZA']);
        Establecimiento::create(['est_id' => '0H081095','est_establecimiento' => '593 LUIS FELIPE DE LAS CASAS GRIEVE']);
        Establecimiento::create(['est_id' => '0H063050','est_establecimiento' => '7053 REINO DE ESPAÑA']);
        Establecimiento::create(['est_id' => '0H062185','est_establecimiento' => '7053 REINO DE ESPAÑA']);
        Establecimiento::create(['est_id' => '0H032217','est_establecimiento' => '7089 ROMEO LUNA VICTORIA']);
        Establecimiento::create(['est_id' => '0H083095','est_establecimiento' => '6082 LOS PROCERES']);
        Establecimiento::create(['est_id' => '0H091200','est_establecimiento' => 'MATELLINI']);
        Establecimiento::create(['est_id' => '0H133060','est_establecimiento' => '7042 SANTA TERESA DE VILLA']);
        Establecimiento::create(['est_id' => '0H051015','est_establecimiento' => 'SANTA CRUZ']);
        Establecimiento::create(['est_id' => '0H063005','est_establecimiento' => '6052 JOSE MARIA EGUREN']);
        Establecimiento::create(['est_id' => '0H052090','est_establecimiento' => '7003 MANUEL FERNANDO BONILLA']);
        Establecimiento::create(['est_id' => '0H021380','est_establecimiento' => 'APOSTOL SAN PEDRO']);
        Establecimiento::create(['est_id' => '0H061075','est_establecimiento' => '6052 JOSE MARIA EGUREN']);
        Establecimiento::create(['est_id' => '0H111105','est_establecimiento' => '7066 ANDRES AVELINO CACERES']);
        Establecimiento::create(['est_id' => '0H121011','est_establecimiento' => '59 SANTA LUCIA']);
        Establecimiento::create(['est_id' => '0H010005','est_establecimiento' => 'UNIDAD DE GESTION EDUCATIVA LOCAL 07 SAN BORJA']);
        Establecimiento::create(['est_id' => '0H091015','est_establecimiento' => '518 LOS ANGELES DE JESUS']);
        Establecimiento::create(['est_id' => '0H131117','est_establecimiento' => '7077 LOS REYES ROJOS']);
        Establecimiento::create(['est_id' => '0H062173','est_establecimiento' => '7050 NICANOR RIVERA CACERES']);
        Establecimiento::create(['est_id' => '0H042135','est_establecimiento' => '7014 VASIL LEVSKI']);
        Establecimiento::create(['est_id' => '0H042195','est_establecimiento' => '7028 MARCO A.SCHENONE OLIVA']);
        Establecimiento::create(['est_id' => '0H102140','est_establecimiento' => '7103 PEDRO PAULET Y MOSTAJO']);
        Establecimiento::create(['est_id' => '0H048015','est_establecimiento' => 'PRITE ALEGRIA EN EL CORAZON']);
        Establecimiento::create(['est_id' => '0H082120','est_establecimiento' => '6082 LOS PROCERES']);
        Establecimiento::create(['est_id' => '0H087080','est_establecimiento' => 'CEBA - 6047 JOSE MARIA ARGUEDAS']);
        Establecimiento::create(['est_id' => '0H131020','est_establecimiento' => '521 VIRGEN MARIA MADRE DE LOS NIÑOS']);
        Establecimiento::create(['est_id' => '0H102035','est_establecimiento' => '6091 CESAR VALLEJO']);
        Establecimiento::create(['est_id' => '0H032500','est_establecimiento' => 'LICEO NAVAL ALMIRANTE GUISE']);
        Establecimiento::create(['est_id' => '0H033018','est_establecimiento' => 'LA DIVINA PROVIDENCIA']);
        Establecimiento::create(['est_id' => '0H063035','est_establecimiento' => '7704 SANTA ROSA']);
        Establecimiento::create(['est_id' => '0H131025','est_establecimiento' => '7042 SANTA TERESA DE VILLA']);
        Establecimiento::create(['est_id' => '0H021320','est_establecimiento' => 'MADRE ADMIRABLE']);
        Establecimiento::create(['est_id' => '0H042125','est_establecimiento' => '7012 JESUS DE LA MISERICORDIA']);
        Establecimiento::create(['est_id' => '0H093063','est_establecimiento' => '7037 ARIOSTO MATELLINI ESPINOZA']);
        Establecimiento::create(['est_id' => '0H125015','est_establecimiento' => 'PILOTO JOSE PARDO']);
        Establecimiento::create(['est_id' => '0H093010','est_establecimiento' => '6085 BRIGIDA SILVA DE OCHOA']);
        Establecimiento::create(['est_id' => '0H062165','est_establecimiento' => '7048 MANUEL MONTERO BERNALES']);
        Establecimiento::create(['est_id' => '0H132117','est_establecimiento' => '7077 LOS REYES ROJOS']);
        Establecimiento::create(['est_id' => '0H132110','est_establecimiento' => '7075 JUAN PABLO II']);
        Establecimiento::create(['est_id' => '0H051010','est_establecimiento' => '15 VIRGEN DE LOURDES']);
        Establecimiento::create(['est_id' => '0H061175','est_establecimiento' => 'C.R.A.E.I. - SURCO']);
        Establecimiento::create(['est_id' => '0H093005','est_establecimiento' => 'SAN PEDRO DE CHORRILLOS']);
        Establecimiento::create(['est_id' => '0H032120','est_establecimiento' => '6079 SANTISIMA NIÑA MARIA']);
        Establecimiento::create(['est_id' => '0H025320','est_establecimiento' => 'SAN PEDRO']);
        Establecimiento::create(['est_id' => '0H043007','est_establecimiento' => '6049 RICARDO PALMA']);
        Establecimiento::create(['est_id' => '0H113052','est_establecimiento' => '7066 ANDRES AVELINO CACERES']);
        Establecimiento::create(['est_id' => '0H102025','est_establecimiento' => '6086 SANTA ISABEL']);
        Establecimiento::create(['est_id' => '0H082110','est_establecimiento' => '6047 JOSE MARIA ARGUEDAS']);
        Establecimiento::create(['est_id' => '0H031033','est_establecimiento' => '554 VIRGEN DE LOURDES']);
        Establecimiento::create(['est_id' => '0H068005','est_establecimiento' => '02 LAURA ALVA SALDAÑA']);
        Establecimiento::create(['est_id' => '0H083105','est_establecimiento' => '7086 LOS PRECURSORES']);
        Establecimiento::create(['est_id' => '0H082090','est_establecimiento' => '6043 PEDRO VENTURO']);
        Establecimiento::create(['est_id' => '0H067020','est_establecimiento' => 'CEBA - 7050 NICANOR RIVERA CACERES']);
        Establecimiento::create(['est_id' => '0H058025','est_establecimiento' => 'ESPECIAL 4']);
        Establecimiento::create(['est_id' => '0H122135','est_establecimiento' => 'COLEGIO PARROQUIAL "NIÑO JESUS DE PRAGA"']);
        Establecimiento::create(['est_id' => '0H034003','est_establecimiento' => 'CEBA - SAN FRANCISCO DE BORJA']);
        Establecimiento::create(['est_id' => '0H131140','est_establecimiento' => '581 LUIS FELIPE DE LAS CASAS']);
        Establecimiento::create(['est_id' => '0H063015','est_establecimiento' => '7047 TACNA']);
        Establecimiento::create(['est_id' => '0H101060','est_establecimiento' => 'COMUNAL SAN JUAN DE LA LIBERTAD']);
        Establecimiento::create(['est_id' => '0H061005','est_establecimiento' => '10 PEDRO DE OSMA']);
        Establecimiento::create(['est_id' => '0H032172','est_establecimiento' => '7022 ALBERT EINSTEIN']);
        Establecimiento::create(['est_id' => '0H078020','est_establecimiento' => '09 SAN FRANCISCO DE ASIS']);
        Establecimiento::create(['est_id' => '0H022335','est_establecimiento' => '1216 MIGUEL GRAU SEMINARIO']);
        Establecimiento::create(['est_id' => '0H047001','est_establecimiento' => 'CEBA - 6049 RICARDO PALMA']);
        Establecimiento::create(['est_id' => '0H053010','est_establecimiento' => '6050 JUANA ALARCO DE DAMMERT']);
        Establecimiento::create(['est_id' => '0H071025','est_establecimiento' => '86']);
        Establecimiento::create(['est_id' => '0H103028','est_establecimiento' => '6086 SANTA ISABEL']);
        Establecimiento::create(['est_id' => '0H081030','est_establecimiento' => '87 LOS PROCERES']);
        Establecimiento::create(['est_id' => '0H081101','est_establecimiento' => 'JESUS ES AMOR']);
        Establecimiento::create(['est_id' => '0H122090','est_establecimiento' => '7044 SAN MARTIN DE PORRES']);
        Establecimiento::create(['est_id' => '0H092125','est_establecimiento' => 'SAN PEDRO DE CHORRILLOS']);
        Establecimiento::create(['est_id' => '0H133030','est_establecimiento' => '6090 JOSE OLAYA BALANDRA']);
        Establecimiento::create(['est_id' => '0H032215','est_establecimiento' => '7083 MANUEL GONZALES PRADA']);
        Establecimiento::create(['est_id' => '0H079100','est_establecimiento' => 'IEI VIRGEN DE LORETO']);
        Establecimiento::create(['est_id' => '0H121200','est_establecimiento' => 'PRIMEROS PASOS']);
        Establecimiento::create(['est_id' => '0H081040','est_establecimiento' => 'VICTORIA BARCIA BONIFATTI']);
        Establecimiento::create(['est_id' => '0H051005','est_establecimiento' => 'JUGANDO PARA CRECER']);
        Establecimiento::create(['est_id' => '0H021385','est_establecimiento' => '1133 SANTISIMA VIRGEN DE FATIMA']);
        Establecimiento::create(['est_id' => '0H082240','est_establecimiento' => '7087 SANTIAGO DE SURCO']);
        Establecimiento::create(['est_id' => '0H072200','est_establecimiento' => '7058 MARIA DE FATIMA']);
        Establecimiento::create(['est_id' => '0H042118','est_establecimiento' => '6049 RICARDO PALMA']);
        Establecimiento::create(['est_id' => '0H052080','est_establecimiento' => '7001 ANDRES BELLO']);
        Establecimiento::create(['est_id' => '0H035025','est_establecimiento' => 'SAN FRANCISCO DE BORJA']);
        Establecimiento::create(['est_id' => '0H042178','est_establecimiento' => '7024']);
        Establecimiento::create(['est_id' => '0H132160','est_establecimiento' => 'LOS INKAS']);
        Establecimiento::create(['est_id' => '0H083801','est_establecimiento' => 'TECNICO FAP MANUEL POLO JIMENEZ']);
        Establecimiento::create(['est_id' => '0H073040','est_establecimiento' => '6044 JORGE CHAVEZ']);
        Establecimiento::create(['est_id' => '0H083055','est_establecimiento' => '6047 JOSE MARIA ARGUEDAS']);
        Establecimiento::create(['est_id' => '0H102055','est_establecimiento' => '6153 CAP.EP. AUGUSTO J GUTIERREZ MENDOZA']);
        Establecimiento::create(['est_id' => '0H097040','est_establecimiento' => 'CEBA - BENJAMIN BLOOM']);
        Establecimiento::create(['est_id' => '0H082185','est_establecimiento' => '6087 PABLO MARIA GUZMAN']);
        Establecimiento::create(['est_id' => '0H133080','est_establecimiento' => 'VIRGEN DEL MORRO SOLAR']);
        Establecimiento::create(['est_id' => '0H098005','est_establecimiento' => 'ESPECIAL 12']);
        Establecimiento::create(['est_id' => '0H113070','est_establecimiento' => '7076 LAS BRISAS DE VILLA']);
        Establecimiento::create(['est_id' => '0H132085','est_establecimiento' => '7042 SANTA TERESA DE VILLA']);
        Establecimiento::create(['est_id' => '0H023340','est_establecimiento' => 'SANTA MATILDE']);
        Establecimiento::create(['est_id' => '0H033040','est_establecimiento' => '7089 ROMEO LUNA VICTORIA']);
        Establecimiento::create(['est_id' => '0H094035','est_establecimiento' => 'CEBA - BENJAMIN BLOOM']);
        Establecimiento::create(['est_id' => '0H065025','est_establecimiento' => 'CARLOS CUETO FERNANDINI']);
        Establecimiento::create(['est_id' => '0H139032','est_establecimiento' => '564 LOS JILGUEROS DE VILLA VENTURO']);
        Establecimiento::create(['est_id' => '0H131101','est_establecimiento' => '7064 MARIA AUXILIADORA']);
        Establecimiento::create(['est_id' => '0H041035','est_establecimiento' => '556 NIÑO JESUS']);
        Establecimiento::create(['est_id' => '0H051179','est_establecimiento' => '42 ELIZABETH ESPEJO DE MARROQUIN']);
        Establecimiento::create(['est_id' => '0H101030','est_establecimiento' => '563 SANTISIMO DIVINO NIÑO JESUS']);
        Establecimiento::create(['est_id' => '0H052075','est_establecimiento' => '6003 REBECA CARRION CACHOT']);
        Establecimiento::create(['est_id' => '0H081070','est_establecimiento' => '555 INMACULADA CONCEPCION']);
        Establecimiento::create(['est_id' => '0H022330','est_establecimiento' => '1133 SANTISIMA VIRGEN DE FATIMA']);
        Establecimiento::create(['est_id' => '0H088005','est_establecimiento' => 'CERCIL']);
        Establecimiento::create(['est_id' => '0H038030','est_establecimiento' => 'INSTITUTO PARA NIÑOS EXCEPCIONALES']);
        Establecimiento::create(['est_id' => '0H112020','est_establecimiento' => '6075 JOSE MARIA ARGUEDAS']);
        Establecimiento::create(['est_id' => '0H041040','est_establecimiento' => '7028 MARCO A.SCHENONE OLIVA']);
        Establecimiento::create(['est_id' => '0H023315','est_establecimiento' => '0083 SAN JUAN MASIAS']);
        Establecimiento::create(['est_id' => '0H038001','est_establecimiento' => 'MARIA AUXILIADORA']);
        Establecimiento::create(['est_id' => '0H133034','est_establecimiento' => '6094 SANTA ROSA']);
        Establecimiento::create(['est_id' => '0H093015','est_establecimiento' => 'JOSE DE LA RIVA AGUERO Y OSMA']);
        Establecimiento::create(['est_id' => '0H031055','est_establecimiento' => 'INEN']);
        Establecimiento::create(['est_id' => '0H112150','est_establecimiento' => 'FE Y ALEGRIA 34']);
        Establecimiento::create(['est_id' => '0H041031','est_establecimiento' => '542 LOS SAUCES']);
        Establecimiento::create(['est_id' => '0H062025','est_establecimiento' => '7049 JOSE ABELARDO QUIÑONES']);
        Establecimiento::create(['est_id' => '0H021305','est_establecimiento' => '004 NIÑO JESUS DE PRAGA']);
        Establecimiento::create(['est_id' => '0H123040','est_establecimiento' => '6053 SAGRADO CORAZON']);
        Establecimiento::create(['est_id' => '0H025340','est_establecimiento' => 'SAN LUIS']);
        Establecimiento::create(['est_id' => '0H021350','est_establecimiento' => '1216 MIGUEL GRAU SEMINARIO']);
        Establecimiento::create(['est_id' => '0H083100','est_establecimiento' => 'ALCIDES VIGO HURTADO']);
        Establecimiento::create(['est_id' => '0H101040','est_establecimiento' => 'BUENOS AIRES DE VILLA']);
        Establecimiento::create(['est_id' => '0H053015','est_establecimiento' => 'FEDERICO VILLARREAL']);
        Establecimiento::create(['est_id' => '0H023330','est_establecimiento' => 'MADRE ADMIRABLE']);
        Establecimiento::create(['est_id' => '0H091080','est_establecimiento' => 'SAN FRANCISCO']);
        Establecimiento::create(['est_id' => '0H063025','est_establecimiento' => '7049 JOSE ABELARDO QUIÑONES']);
        Establecimiento::create(['est_id' => '0H043045','est_establecimiento' => '7014 VASIL LEVSKI']);
        Establecimiento::create(['est_id' => '0H067010','est_establecimiento' => 'CEBA - 6051 MERCEDES INDACOCHEA']);
        Establecimiento::create(['est_id' => '0H037007','est_establecimiento' => 'CEBA - 7089 ROMEO LUNA VICTORIA']);
        Establecimiento::create(['est_id' => '0H048010','est_establecimiento' => 'SANTA MARIA DE GUADALUPE']);
        Establecimiento::create(['est_id' => '0H099075','est_establecimiento' => 'NAZARETH']);
        Establecimiento::create(['est_id' => '0H121120','est_establecimiento' => 'CAPULLITOS DE JESUS']);
        Establecimiento::create(['est_id' => '0H072220','est_establecimiento' => '7068 ABRAHAM ROLDAN POMA']);
        Establecimiento::create(['est_id' => '0H023320','est_establecimiento' => '1204 VILLA JARDIN']);
        Establecimiento::create(['est_id' => '0H022320','est_establecimiento' => '1204 VILLA JARDIN']);
        Establecimiento::create(['est_id' => '0H125005','est_establecimiento' => 'JOSE OLAYA']);
        Establecimiento::create(['est_id' => '0H057042','est_establecimiento' => 'CEBA - 6050 JUANA ALARCO DE DAMMERT']);
        Establecimiento::create(['est_id' => '0H101012','est_establecimiento' => '7039 MANUEL SCORZA TORRES']);
        Establecimiento::create(['est_id' => '0H112115','est_establecimiento' => '7076 LAS BRISAS DE VILLA']);
        Establecimiento::create(['est_id' => '0H023310','est_establecimiento' => 'LOS EDUCADORES']);
        Establecimiento::create(['est_id' => '0H112105','est_establecimiento' => '7066 ANDRES AVELINO CACERES']);
        Establecimiento::create(['est_id' => '0H022315','est_establecimiento' => 'MADRE ADMIRABLE']);
        Establecimiento::create(['est_id' => '0H063040','est_establecimiento' => '7050 NICANOR RIVERA CACERES']);
        Establecimiento::create(['est_id' => '0H103035','est_establecimiento' => '7039 MANUEL SCORZA TORRES']);
        Establecimiento::create(['est_id' => '0H022305','est_establecimiento' => '0082 LA CANTUTA']);
        Establecimiento::create(['est_id' => '0H071050','est_establecimiento' => '536 AMIGUITOS DE JESUS']);
        Establecimiento::create(['est_id' => '0H022325','est_establecimiento' => '1128 SAN LUIS']);
        Establecimiento::create(['est_id' => '0H103042','est_establecimiento' => '6097 MATEO PUMACAHUA']);
        Establecimiento::create(['est_id' => '0H091005','est_establecimiento' => 'PEDRO RUIZ GALLO']);
        Establecimiento::create(['est_id' => '0H113055','est_establecimiento' => 'FE Y ALEGRIA 34']);
        Establecimiento::create(['est_id' => '0H021335','est_establecimiento' => '133 FERNANDO LUNA DEMUTTI']);
        Establecimiento::create(['est_id' => '0H132100','est_establecimiento' => '7064 MARIA AUXILIADORA']);
        Establecimiento::create(['est_id' => '0H062130','est_establecimiento' => '7043 CORAZON DE JESUS']);
        Establecimiento::create(['est_id' => '0H102080','est_establecimiento' => '7039 MANUEL SCORZA TORRES']);
        Establecimiento::create(['est_id' => '0H063020','est_establecimiento' => 'ENRIQUE ARNAEZ NAVEDA']);
        Establecimiento::create(['est_id' => '0H063045','est_establecimiento' => 'VIRGEN DE FATIMA DE BARRANCO']);
        Establecimiento::create(['est_id' => '0H033028','est_establecimiento' => 'NUESTRA SEÑORA DE LOURDES']);
        Establecimiento::create(['est_id' => '0H102050','est_establecimiento' => '6097 MATEO PUMACAHUA']);
        Establecimiento::create(['est_id' => '0H097010','est_establecimiento' => 'CEBA - 6085 BRIGIDA SILVA DE OCHOA']);
        Establecimiento::create(['est_id' => '0H117035','est_establecimiento' => 'CEBA - 6097 MATEO PUMACAHUA']);
        Establecimiento::create(['est_id' => '0H073060','est_establecimiento' => 'VIRGEN DEL ROSARIO']);
        Establecimiento::create(['est_id' => '0H083110','est_establecimiento' => '6087 PABLO MARIA GUZMAN']);
        Establecimiento::create(['est_id' => '0H123065','est_establecimiento' => '7038 CORAZON DE JESUS DE ARMATAMBO']);
        Establecimiento::create(['est_id' => '0H103033','est_establecimiento' => '6091 CESAR VALLEJO']);
        Establecimiento::create(['est_id' => '0H062510','est_establecimiento' => 'VIRGEN DE FATIMA DE BARRANCO']);
        Establecimiento::create(['est_id' => '0H072005','est_establecimiento' => 'VIRGEN DEL ROSARIO']);
        Establecimiento::create(['est_id' => '0H087030','est_establecimiento' => 'CEBA - 6043 PEDRO VENTURO']);
        Establecimiento::create(['est_id' => '0H068010','est_establecimiento' => '07 LA INMACULADA']);
        Establecimiento::create(['est_id' => '0H123062','est_establecimiento' => '7034 ENRIQUE NERINI COLLAZOS']);
        Establecimiento::create(['est_id' => '0H071085','est_establecimiento' => 'SAN FRANCISCO DE ASIS']);
        Establecimiento::create(['est_id' => '0H057045','est_establecimiento' => 'CEBA - FEDERICO VILLARREAL']);
        Establecimiento::create(['est_id' => '0H084030','est_establecimiento' => 'CEBA - 6043 PEDRO VENTURO']);
        Establecimiento::create(['est_id' => '0H071045','est_establecimiento' => 'VIRGEN DEL ROSARIO']);
        Establecimiento::create(['est_id' => '0H125010','est_establecimiento' => '6053 SAGRADO CORAZON']);
        Establecimiento::create(['est_id' => '0H131125','est_establecimiento' => '567 MI PEQUEÑO PEDRO']);
        Establecimiento::create(['est_id' => '0H062160','est_establecimiento' => '7047 TACNA']);
        Establecimiento::create(['est_id' => '0H061174','est_establecimiento' => '7047 TACNA']);
        Establecimiento::create(['est_id' => '0H134040','est_establecimiento' => 'CEBA - 6090 JOSE OLAYA BALANDRA']);
        Establecimiento::create(['est_id' => '0H131035','est_establecimiento' => 'COMUNAL SANTA TERESA']);
        Establecimiento::create(['est_id' => '0H133086','est_establecimiento' => '7077 LOS REYES ROJOS']);
        Establecimiento::create(['est_id' => '0H093100','est_establecimiento' => 'PEDRO RUIZ GALLO']);
        Establecimiento::create(['est_id' => '0H071062','est_establecimiento' => '538 LAS PALMAS']);
        Establecimiento::create(['est_id' => '0H071105','est_establecimiento' => '7068 ABRAHAM ROLDAN POMA']);
        Establecimiento::create(['est_id' => '0H023305','est_establecimiento' => '0082 LA CANTUTA']);
        Establecimiento::create(['est_id' => '0H032200','est_establecimiento' => '7029 VIRGEN MILAGROSA']);
        Establecimiento::create(['est_id' => '0H062085','est_establecimiento' => '7032 VIRGEN DEL PILAR']);
        Establecimiento::create(['est_id' => '0H137025','est_establecimiento' => 'CEBA - 6090 JOSE OLAYA BALANDRA']);
        Establecimiento::create(['est_id' => '0H061173','est_establecimiento' => '7050 NICANOR RIVERA CACERES']);
        Establecimiento::create(['est_id' => '0H043033','est_establecimiento' => 'SAN VICENTE DE PAUL']);
        Establecimiento::create(['est_id' => '0H122010','est_establecimiento' => '6053 SAGRADO CORAZON']);
        Establecimiento::create(['est_id' => '0H135015','est_establecimiento' => 'SANTA TERESA']);
        Establecimiento::create(['est_id' => '0H041007','est_establecimiento' => '6049 RICARDO PALMA']);
        Establecimiento::create(['est_id' => '0H053022','est_establecimiento' => '7008 SCIPION LLONA']);
        Establecimiento::create(['est_id' => '0H062030','est_establecimiento' => '7704 SANTA ROSA']);
        Establecimiento::create(['est_id' => '0H131118','est_establecimiento' => 'MADRE TERESA']);
        Establecimiento::create(['est_id' => '0H058015','est_establecimiento' => 'TOÑITO SILVA GUERRERO']);
        Establecimiento::create(['est_id' => '0H088060','est_establecimiento' => 'ESPECIAL SURCO']);
        Establecimiento::create(['est_id' => '0H041020','est_establecimiento' => '53 MI NIÑITO JESUS']);
        Establecimiento::create(['est_id' => '0H081065','est_establecimiento' => 'URPI WASSI']);
        Establecimiento::create(['est_id' => '0H132005','est_establecimiento' => 'ARQUITECTO FERNANDO BELAUNDE TERRY']);
        Establecimiento::create(['est_id' => '0H131150','est_establecimiento' => '6090 JOSE OLAYA BALANDRA']);
        Establecimiento::create(['est_id' => '0H027325','est_establecimiento' => 'CEBA - 1128 SAN LUIS']);
        Establecimiento::create(['est_id' => '0H131080','est_establecimiento' => 'VIRGEN DEL MORRO SOLAR']);
        Establecimiento::create(['est_id' => '0H133051','est_establecimiento' => '7064 MARIA AUXILIADORA']);
        Establecimiento::create(['est_id' => '0H077060','est_establecimiento' => 'CEBA - 6044 JORGE CHAVEZ']);
        Establecimiento::create(['est_id' => '0H122060','est_establecimiento' => '7034 ENRIQUE NERINI COLLAZOS']);
        Establecimiento::create(['est_id' => '0H052115','est_establecimiento' => '7008 SCIPION LLONA']);
        Establecimiento::create(['est_id' => '0H067005','est_establecimiento' => 'CEBA - 6052 JOSE MARIA EGUREN']);
        Establecimiento::create(['est_id' => '0H137020','est_establecimiento' => 'CEBA - 7075 JUAN PABLO II']);
        Establecimiento::create(['est_id' => '0H111065','est_establecimiento' => 'COMUNAL DELICIAS DE VILLA']);
        Establecimiento::create(['est_id' => '0H131119','est_establecimiento' => '570 INTEGRACION']);
        Establecimiento::create(['est_id' => '0H131145','est_establecimiento' => 'LOS INKAS']);
        Establecimiento::create(['est_id' => '0H134020','est_establecimiento' => 'CEBA - 7075 JUAN PABLO II']);
        Establecimiento::create(['est_id' => '0H121067','est_establecimiento' => '7036 ANGELICA RECHARTE CORRALES']);
        Establecimiento::create(['est_id' => '0H095025','est_establecimiento' => 'MARIA PARADO DE BELLIDO']);
        Establecimiento::create(['est_id' => '0H114035','est_establecimiento' => 'CEBA - 6097 MATEO PUMACAHUA']);
        Establecimiento::create(['est_id' => '0H121061','est_establecimiento' => '7034 ENRIQUE NERINI COLLAZOS']);
        Establecimiento::create(['est_id' => '0H111045','est_establecimiento' => '6075 JOSE MARIA ARGUEDAS']);
        Establecimiento::create(['est_id' => '0H025350','est_establecimiento' => 'MADRE ADMIRABLE']);
        Establecimiento::create(['est_id' => '0H087090','est_establecimiento' => 'CEBA - MARIA INMACULADA']);
        Establecimiento::create(['est_id' => '0H122120','est_establecimiento' => '7707 CRISTO REY']);
        Establecimiento::create(['est_id' => '0H105055','est_establecimiento' => 'VISTA ALEGRE DE VILLA']);
        Establecimiento::create(['est_id' => '0H111050','est_establecimiento' => 'MILAGRITOS DE JESUS']);
        Establecimiento::create(['est_id' => '0H131160','est_establecimiento' => 'PRIMERO DE MAYO 2']);
        Establecimiento::create(['est_id' => '0H054010','est_establecimiento' => 'CEBA - 6050 JUANA ALARCO DE DAMMERT']);
        Establecimiento::create(['est_id' => '0H101155','est_establecimiento' => '6097 MATEO PUMACAHUA']);
        Establecimiento::create(['est_id' => '0H111095','est_establecimiento' => 'JESUS MAESTRO']);
        Establecimiento::create(['est_id' => '0H063030','est_establecimiento' => '7701 NUESTRA SEÑORA DEL CARMEN']);
        Establecimiento::create(['est_id' => '0H031028','est_establecimiento' => '522 MARIA INMACULADA']);
        Establecimiento::create(['est_id' => '0H041025','est_establecimiento' => '79 VIRGEN DEL CARMEN']);
        Establecimiento::create(['est_id' => '0H022350','est_establecimiento' => 'APOSTOL SAN PEDRO']);
        Establecimiento::create(['est_id' => '0H021310','est_establecimiento' => '0082 LA CANTUTA']);
        Establecimiento::create(['est_id' => '0H064030','est_establecimiento' => 'CEBA - 7050 NICANOR RIVERA CACERES']);
        Establecimiento::create(['est_id' => '0H042210','est_establecimiento' => 'SAN VICENTE DE PAUL']);
        Establecimiento::create(['est_id' => '0H044007','est_establecimiento' => 'CEBA - 6049 RICARDO PALMA']);
        Establecimiento::create(['est_id' => '0H041179','est_establecimiento' => '7031 REINA DE LA FAMILIA']);
        Establecimiento::create(['est_id' => '0H092100','est_establecimiento' => 'PEDRO RUIZ GALLO']);
        Establecimiento::create(['est_id' => '0H085045','est_establecimiento' => 'MARIA INMACULADA']);
        Establecimiento::create(['est_id' => '0H121205','est_establecimiento' => '7038 CORAZON DE JESUS DE ARMATAMBO']);
        Establecimiento::create(['est_id' => '0H084060','est_establecimiento' => 'CEBA - MARIA INMACULADA']);
        Establecimiento::create(['est_id' => '0H101110','est_establecimiento' => 'MAHATMA GANDHI']);
        Establecimiento::create(['est_id' => '0H123045','est_establecimiento' => 'COLEGIO PARROQUIAL "NIÑO JESUS DE PRAGA"']);
        Establecimiento::create(['est_id' => '0H082801','est_establecimiento' => 'COLEGIO FAP POLO JIMENEZ']);
        Establecimiento::create(['est_id' => '0H081080','est_establecimiento' => '557 WARMA KUYAY']);
        Establecimiento::create(['est_id' => '0H037015','est_establecimiento' => 'CEBA - SAN FRANCISCO DE BORJA']);
        Establecimiento::create(['est_id' => '0H082225','est_establecimiento' => '7086 LOS PRECURSORES']);
        Establecimiento::create(['est_id' => '0H022345','est_establecimiento' => 'LOS EDUCADORES']);
        Establecimiento::create(['est_id' => '0H028305','est_establecimiento' => 'MADRE ADMIRABLE']);
        Establecimiento::create(['est_id' => '0H131005','est_establecimiento' => 'ARQUITECTO FERNANDO BELAUNDE TERRY']);
        Establecimiento::create(['est_id' => '0H088025','est_establecimiento' => 'CPAL FERNANDO WIESE ESLAVA']);
        Establecimiento::create(['est_id' => '0H081100','est_establecimiento' => 'MI CASITA FELIZ 2']);
        Establecimiento::create(['est_id' => '0H131155','est_establecimiento' => 'MIS ANGELITOS I']);
        Establecimiento::create(['est_id' => '0H051078','est_establecimiento' => '6050 JUANA ALARCO DE DAMMERT']);
        Establecimiento::create(['est_id' => '0H031120','est_establecimiento' => '6079 SANTISIMA NIÑA MARIA']);
        Establecimiento::create(['est_id' => '0H031035','est_establecimiento' => '7083 MANUEL GONZALES PRADA']);
        Establecimiento::create(['est_id' => '0H054045','est_establecimiento' => 'CEBA - FEDERICO VILLARREAL']);
        Establecimiento::create(['est_id' => '0H091062','est_establecimiento' => 'LA ESPERANZA']);
        Establecimiento::create(['est_id' => '0H091100','est_establecimiento' => 'MARIA PARADO DE BELLIDO']);
        Establecimiento::create(['est_id' => '0H118010','est_establecimiento' => 'PRITE']);
        Establecimiento::create(['est_id' => '0H055010','est_establecimiento' => 'SANTA CRUZ']);
        Establecimiento::create(['est_id' => '0H062005','est_establecimiento' => '7701 NUESTRA SEÑORA DEL CARMEN']);
        Establecimiento::create(['est_id' => '0H033400','est_establecimiento' => 'TUTORIA Y PREVENCION INTEGRAL']);
        Establecimiento::create(['est_id' => '0H081075','est_establecimiento' => '6087 PABLO MARIA GUZMAN']);
        Establecimiento::create(['est_id' => '0H082230','est_establecimiento' => 'ALCIDES VIGO HURTADO']);
        Establecimiento::create(['est_id' => '0H042190','est_establecimiento' => '7027 NUESTRA SEÑORA DE LA ALEGRIA']);
        Establecimiento::create(['est_id' => '0H098050','est_establecimiento' => 'SANTA ISABEL']);
        Establecimiento::create(['est_id' => '0H081801','est_establecimiento' => 'COLEGIO FAP POLO JIMENEZ']);
        Establecimiento::create(['est_id' => '0H101033','est_establecimiento' => '6091 CESAR VALLEJO']);
        Establecimiento::create(['est_id' => '0H084035','est_establecimiento' => 'CEBA - 6047 JOSE MARIA ARGUEDAS']);
        Establecimiento::create(['est_id' => '0H042205','est_establecimiento' => '7031 REINA DE LA FAMILIA']);
        Establecimiento::create(['est_id' => '0H125050','est_establecimiento' => 'MUNICIPAL DE CHORRILLOS']);
        Establecimiento::create(['est_id' => '0H101130','est_establecimiento' => '568 VIRGEN DE FATIMA']);
        Establecimiento::create(['est_id' => '0H034006','est_establecimiento' => 'CEBA - 7089 ROMEO LUNA VICTORIA']);
        Establecimiento::create(['est_id' => '0H081102','est_establecimiento' => '7086 LOS PRECURSORES']);
        Establecimiento::create(['est_id' => '0H064010','est_establecimiento' => 'CEBA - 6051 MERCEDES INDACOCHEA']);
        Establecimiento::create(['est_id' => '0H064005','est_establecimiento' => 'CEBA - 6052 JOSE MARIA EGUREN']);
        Establecimiento::create(['est_id' => '0H123075','est_establecimiento' => '7707 CRISTO REY']);
        Establecimiento::create(['est_id' => '0H112350','est_establecimiento' => 'LICEO NAVAL CAP. NAVIO "JUAN FANNING GARCÍA"']);
        Establecimiento::create(['est_id' => '0H024325','est_establecimiento' => 'CEBA - 1128 SAN LUIS']);
        Establecimiento::create(['est_id' => '0H094010','est_establecimiento' => 'CEBA - 6085 BRIGIDA SILVA DE OCHOA']);
        Establecimiento::create(['est_id' => '0H121115','est_establecimiento' => '7707 CRISTO REY']);
        Establecimiento::create(['est_id' => '0H031500','est_establecimiento' => 'LICEO NAVAL ALMIRANTE GUISE']);
        Establecimiento::create(['est_id' => '0H033500','est_establecimiento' => 'LICEO NAVAL ALMIRANTE GUISE']);
        Establecimiento::create(['est_id' => '0H079125','est_establecimiento' => 'CUNA SAN GABINO']);
        Establecimiento::create(['est_id' => '0H102110','est_establecimiento' => 'MAHATMA GANDHI']);
        Establecimiento::create(['est_id' => '0H072001','est_establecimiento' => 'OFICINA DE EDUCACIÓN CATÓLICA DEL ARZOBISPADO DE LIMA (ODEC-LIMA)']);
        Establecimiento::create(['est_id' => '0H113350','est_establecimiento' => 'LICEO NAVAL CAP. NAVIO "JUAN FANNING GARCÍA"']);
        Establecimiento::create(['est_id' => '0H022340','est_establecimiento' => 'SANTA MATILDE']);
        Establecimiento::create(['est_id' => '0H023345','est_establecimiento' => 'APOSTOL SAN PEDRO']);
        Establecimiento::create(['est_id' => '0H115030','est_establecimiento' => 'TUPAC AMARU']);
        Establecimiento::create(['est_id' => '0H041178','est_establecimiento' => '7024']);
        Establecimiento::create(['est_id' => '0H074065','est_establecimiento' => 'CEBA - 6044 JORGE CHAVEZ']);
        Establecimiento::create(['est_id' => '0H111160','est_establecimiento' => 'FE Y ALEGRIA 34']);
        Establecimiento::create(['est_id' => '0H121090','est_establecimiento' => 'NIÑO JESUS DE PRAGA']);
        Establecimiento::create(['est_id' => '0H08V050','est_establecimiento' => 'COLEGIO ESPECIAL COM.FAP OSCAR OVIDIO MUÑOZ GALLARDO']);
        Establecimiento::create(['est_id' => '0H021355','est_establecimiento' => 'SANTA MATILDE']);
        Establecimiento::create(['est_id' => '0H088050','est_establecimiento' => 'COLEGIO ESPECIAL COM.FAP OSCAR OVIDIO MUÑOZ GALLARDO']);
        Establecimiento::create(['est_id' => '0H082241','est_establecimiento' => 'APLICACION IPNM']);
        Establecimiento::create(['est_id' => '0H039010','est_establecimiento' => 'NIÑO JESUS DE PRAGA - SAN BORJA']);
        Establecimiento::create(['est_id' => '0H085055','est_establecimiento' => 'C.E.O. SAN ROQUE']);
        Establecimiento::create(['est_id' => '0H06V005','est_establecimiento' => '02 LAURA ALVA SALDAÑA']);
        Establecimiento::create(['est_id' => '0H05V015','est_establecimiento' => 'TOÑITO SILVA GUERRERO']);
        Establecimiento::create(['est_id' => '0H02V320','est_establecimiento' => 'TALENTOSOS SOBRESALIENTES']);
        Establecimiento::create(['est_id' => '0H04V035','est_establecimiento' => 'ESPECIAL SURQUILLO']);
        Establecimiento::create(['est_id' => '0H08V025','est_establecimiento' => 'CPAL FERNANDO WISE ESLABA']);
        Establecimiento::create(['est_id' => '0H06V010','est_establecimiento' => '07 LA INMACULADA']);
        Establecimiento::create(['est_id' => '0H09V050','est_establecimiento' => 'SANTA ISABEL']);
        Establecimiento::create(['est_id' => '0H08V060','est_establecimiento' => 'ESPECIAL SURCO']);
        Establecimiento::create(['est_id' => '0H07V020','est_establecimiento' => '09 SAN FRANCISCO DE ASIS']);
        Establecimiento::create(['est_id' => '0H034030','est_establecimiento' => 'INSTITUTO PARA NIÑOS EXCEPCIONALES']);
        Establecimiento::create(['est_id' => '0H033025','est_establecimiento' => 'DIVINA PROVIDENCIA SURQUILLO']);


    }
}
